### ISSUE TITLE
Broken 4.3.4-1ubuntu1

### ISSUE THREAD

**Issue by juanpc2018** [PhoenicisOrg/phoenicis#2530]
ubuntu-focal-multiverse
Reopsitory

pearOS Monterey "Debian/Kubuntu type"

debug claims i need to install wine32
but i have installed wine32 and wine64 v5

**Comment by juanpc2018** [comment]
Manual install seem to work ok

.deb
wine 
xterm

**Comment by juanpc2018** [comment]
wine32 does Not work with 7.4
works with system

**Comment by juanpc2018** [comment]
Trying to Run APTuner 3.09

05/03/22 11:50:10] - Running wine- tuner.exe (Working directory : /home/pearOS/.PlayOnLinux/wineprefix/x86/drive_c/Program Files/AP Tuner/AP Tuner 3.09)
[05/03/22 11:50:18] - Running wine- tuner.exe (Working directory : /home/pearOS/.PlayOnLinux/wineprefix/x86/drive_c/Program Files/AP Tuner/AP Tuner 3.09)
0009:err:module:import_dll Loading library gdiplus.dll (which is needed by L"C:\\Program Files\\AP Tuner\\AP Tuner 3.09\\tuner.exe") failed (error c000007b).
0009:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files\\AP Tuner\\AP Tuner 3.09\\tuner.exe" failed, status c0000135

Install components 
gdiplus 
install = Broken.
